name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '15 */4 * * *'  # Uruchamia się co 4 godziny, o 15 minut po pełnej godzinie
  workflow_dispatch:  # Umożliwia ręczne uruchomienie workflow do testowania

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create empty commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Empty commit to keep Streamlit app active"
          git push 